### ISSUE TITLE
Moving in wrong direction inside projection pools

### ISSUE THREAD

**Issue by SeekerFS** [Raicuparta/nomai-vr#428] opened 2021-08-17 23:42 UTC
* Game Version: Latest
* OWML Version: 1.1.8
* NomaiVR Version: 1.2.2
* VR hardware: Quest 2

When I activate a projection pool by inserting the projection stone, then my movement directions are wrong inside the projection. For example I move left joystick up to walk forwards and I go sideways. I move the joystick sideways and I go forward. Probably because the projection location is rotated differently to my real location and the movement is applied on my character at the projector location in the direction relative to the camera at the relatively rotated projected location.  
So I think this could be fixed if you rotated the movement input by the rotation difference between those 2 locations while in an active projection pool.

**Comment by Raicuparta** [comment] 2021-08-18 04:16
Duplicate of #228

**Closed by Raicuparta** 2021-08-18 04:16 UTC
Labels: bug

**Comment by MLGityaJtotheA** [comment] 2025-03-19 00:41
Hi, this is marked as completed but I'm actually still experiencing this exact issue. I can 'fix' this by facing the direction I move towards when pushing the left joystick forward, and then keeping still physically and looking around horizontally with just the right joystick, but is clearly not meant to work that way.

I can't check the versions right now, but I have all the latest updates for OW, OWML and NomaiVR. I'm using the Quest 3 over steam link.
