### ISSUE TITLE
movement controls not working in multiple different ways. valve index controllers

### ISSUE THREAD

**Issue by goingmental** [Raicuparta/nomai-vr#379] opened 2020-12-21 00:58 UTC
* Game Version: 
* OWML Version:
* NomaiVR Version:
* VR hardware:

 
every time i try to walk with the index controllers i end up walking in circles, and it seems like all of a sudden i just start jumping randomly. what button is this? none of the buttons im pressing do anything of the sort to make me jump. Not to mention the stuttering. I've tried all the different refresh rates to no avail and it seems practically unplayable with how much stuttering is happening and the lack of being able to move. It's not a grip problem either because I've tried moving just the analog stick and the same running in circle problem happens. I'm on the latest version of everything as of 12/20/20 :)

thanks :)

**Comment by Raicuparta** [comment] 2020-12-21 01:28
Closing this as it's a duplicate of #307

Try making a new profile. If that doesn't help, I can't do anything else to help you.

**Closed by Raicuparta** 2020-12-21 01:28 UTC
Labels: bug
