### ISSUE TITLE
Camera probe retrieval when in spaceship doesn't always work

### ISSUE THREAD

**Issue by KungFuJoe23** [Raicuparta/nomai-vr#372] opened 2020-08-26 16:58 UTC
Left hand grip + B doesn't always retrieve a launched camera probe when flying in the spaceship.  Using Oculus Quest + Link. All other controls appear to work fine, including camera probe retrieval when outside of ship.

**Comment by Raicuparta** [comment] 2020-08-26 16:59
It's supposed to be right hand grips not left. Or did you change the defaults?

**Comment by KungFuJoe23** [comment] 2020-08-26 21:24
Sorry I may have mistyped that.  I basically follow the pop up instructions that tell you what to press for the action you desire.  It works sometimes...but often doesn't.  Only happens when in the spaceship.  When using the handheld camera probe, it works 100%.

**Comment by Raicuparta** [comment] 2020-08-26 21:29
Hm, don't know. It's hard for me to diagnose it with such little info on how to reproduce. If you can eventually figure out what actually triggers the bug, that would be very helpful.

**Comment by infernoinugami** [comment] 2020-12-08 00:33
Hi ! I have the exact same problem, once the scout cam sent with the space ship, it becomes impossible to retreive it, b button still working but not the right hand grip button. Tried to leave the ship and retreive it with the tool but no response, only taking photos after that. 
Another problem is in the game menu, whenever i try to acces it after a few minutes (audio settings), the selected items go far left, as if a button is triggered but nothing happening irl. Maybe theses two are related i dont know ? 

Setup for vr is the oculus quest recognised in steam as rift, with touch controllers

**Comment by Nosliwak** [comment] 2021-02-02 08:00
I seem to be getting the same bug, using a Rift S with Touch controllers. haven't touched the default bindings.
I'm able to consistently produce the bug by firing the scout into the Quantum Moon. hopefully that helps.
I actually discovered it because I was trying to snap a photo of the moon but lost it in there, which is unfortunate because it basically renders the ships scout useless for the remainder of that loop.

Also want to say awesome work on the mod!

**Comment by JpTiger** [comment] 2021-02-10 19:46
I also had this issue with Quest and AMD ReviveVR while on Giant's Deep. Maybe the scout got sucked into a tornado or fell beneath the current?

**Comment by Raicuparta** [comment] 2021-03-03 12:01
Fixed in 1.0.3

**Closed** 2021-03-03 12:01 UTC
Labels: bug
