### ISSUE TITLE
(Valve Index) Walking in circles issue

### ISSUE THREAD

**Issue by Ryan-Kilmer** [Raicuparta/nomai-vr#381] opened 2021-02-07 17:43 UTC
First of all this mod is awesome (or well it seems awesome) so thank you for making this!  It looks like you put a lot of great work into it and made a lot of people happy so that's awesome!  (even if I can't get it to work for me) :)

I encountered an issue where my character constantly walks in a circle when I push either the left or right stick forward/backwards on my Valve Index (playing the game through Steam).  It's as if each stick is bound to both look and move control inputs so it does both at the same time causing my character to walk in a circle (although in SteamVR controller bindings left stick is only bound to move and right stick is only bound to look).  [Here is a little video of what it looks like](https://www.youtube.com/watch?v=T1jaH-fLsQw).  In the video I am pushing only the left stick forwards and then I switch to pushing it backwards when I switch directions.  Also I tried both gripping the knuckles controller and not gripping the knuckles controller and got the same results.  I also tried switching forward orientation from head to left controller and that didn't change anything either.

 I Just wanted to ask and see if you have any idea what might be happening here and if I can fix it.  :)

**Comment by Raicuparta** [comment] 2021-02-07 17:46
Closing this as a duplicate of #307. Read the conversation there. Particularly the part about making a new profile.

**Closed by Raicuparta** 2021-02-07 17:46 UTC

**Comment by Ryan-Kilmer** [comment] 2021-02-07 17:58
Yep that worked.  Thank you!
