### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by Mazllo** [Raicuparta/nomai-vr#506] opened 2022-04-16 21:22 UTC
Hi, 
i have seen this bug reported, but its pretty old and inconclusive and i want to make a new thread so it gets seen. Everything was done by the instrucitions and was reinstalled multiple times just to be sure. But when i start the game through mod manager i get this message: 

<html>
<body>

Client disconnected from console | Mod Manager |  
-- | -- | --
Client connected to console | Mod Manager |  
Started OWML v2.3.3 | OWML |  
Game found in C:/Program Files (x86)/Steam/steamapps/common/Outer Wilds | OWML |  
Game version: 1.1.12.201 | OWML |  
Game version is supported | OWML |  
Game files copied. | OWML |  
Found mods: | OWML |  
* Raicuparta.NomaiVR v2.6.0 | OWML |  
Copying OWML files... | OWML |  
Copying replacement OW files... | OWML |  
Patching OW assembly... | OWML |  
Executing patcher for Raicuparta.NomaiVR v2.6.0 | OWML |  
Identified as a Steam install. Launching... | OWML |  
Client disconnected from console | Mod Manager |  
Client connected to console | Mod Manager |  
Mod loader has been initialized. | OWML |  
Game version: 1.1.12.201 | OWML |  
Error updating AppManifest: System.NullReferenceException: Object reference not set to an instance of an objectat NomaiVR.Helpers.ApplicationManifestHelper.UpdateManifest (System.String manifestPath, System.String appKey, System.String imagePath, System.String name, System.String description, System.Int32 steamAppId, System.Boolean steamBuild) [0x0005c] in <e4219433a66b401fb262aad68b496dd0>:0 | NomaiVR |  
NullReferenceException: Object reference not set to an instance of an objectStacktrace: NomaiVR.NomaiVR.InitSteamVR () (at <e4219433a66b401fb262aad68b496dd0>:0)NomaiVR.NomaiVR.ApplyMod () (at <e4219433a66b401fb262aad68b496dd0>:0)NomaiVR.Loaders.NomaiVRLoaderOwml.Start () (at <e4219433a66b401fb262aad68b496dd0>:0) | OWML

</body>
</html>

The game starts on PC but doesnt pick up on the VR headset
* VR hardware: Quest 2
Dont know how to fix this on my own. Could you help me?

**Comment by Raicuparta** [comment] 2022-04-17 10:10
As you said, this is a duplicate of #488, so I'm closing this issue.

**Closed by Raicuparta** 2022-04-17 10:10 UTC
Labels: bug

**Comment by Raicuparta** [comment] 2022-04-17 10:12
I also left a comment in the original
