### ISSUE TITLE
Bug: you can only grab the items on your holsters when they are in your FOV

### ISSUE THREAD

**Issue by NSExceptional** [Raicuparta/nomai-vr#416] opened 2021-05-27 03:40 UTC
I would expect to be able to grab them without looking at them at all. This goes well with my previous feature request about vibrating as your hand passes over them

**Comment by Raicuparta** [comment] 2021-05-27 08:12
Don't think this is an actual bug. I think the problem is that when you look around your body rotates, so your belt rotates too. Since you're not seeing the belt rotate, it might be tripping you up. I grab stuff from the holsters without looking all the time, even looking directly upwards it works fine. So I'll close this unless you have some specific conditions that are triggering a bug, but I do agree that #415 is a good suggestion to make this work better.

**Closed** 2021-05-27 08:13 UTC
Labels: bug

**Comment by NSExceptional** [comment] 2021-05-27 19:18
When you look around, the belt does not rotate (that much); it is supposed to stay mostly in place. The belt does not move with you when you turn.

That said, yeah, I could just be missing it. I'll do some more testing and wait on #415 to see if it helps!

**Comment by Raicuparta** [comment] 2021-05-27 19:23
The belt turns slowly if you're looking down, but it turns quickly if you're looking forward.

**Comment by NSExceptional** [comment] 2021-05-27 23:32
Oh, gotcha. That makes sense.
