### ISSUE TITLE
Ships thrust readout is maxed at 4 notches

### ISSUE THREAD

**Issue by SpikeEscape** [Raicuparta/nomai-vr#74] opened 2020-01-27 03:18 UTC
I also noticed that when operating the ships thrusters that the thrust direction readout actually maxes out at the fourth notch, possibly meaning that it can't reach full speed for some reason?

I'm unsure whether this is cosmetic or if it actually lowers the max thrust possible.

**Comment by Raicuparta** [comment] 2020-01-27 18:46
Fur thrusting up / down I'm getting the 5 notches, but all the other directions I get max 4. Probably need to define a max value for the inputs. Hopefully that's possible via SteamVR's input configs.

**Comment by Raicuparta** [comment] 2020-01-27 18:57
There's a config on SteamVR to change the deadzone for the analog sticks. Can you check if adjusting those helps?

**Comment by SpikeEscape** [comment] 2020-01-27 20:21
My deadzone was already set at 0, and adjusting it didn't seem to make any difference to getting the thrust to 5 notches

**Comment by Raicuparta** [comment] 2020-01-28 00:56
@SpikeEscape Just to clarify, do you mean in the up / down directions, or the others? Or all?

**Comment by SpikeEscape** [comment] 2020-01-28 01:32
Oh yeah the up and down directions right properly for me too, I believe that works because up and down are set to the triggers on the touch controls,

But the directions mapped to the analog stick seem to max out at 4 notches

**Comment by Raicuparta** [comment] 2020-01-28 02:46
OK after investigating this I'm not sure what the problem is. I tried forcing the input values to 1 (the maximum) and it still doesn't get me the full 5 notches.

I'll drop this for now since it doesn't seem to affect gameplay, but I'll leave here some notes for when I come back to it.

I noticed that with a regular XBox controller, if I'm not aiming exactly in the direction of one axis, it will go down to 4 notches in that axis, before it lights up the first notch in the next axis. For instance, if I throttle exactly to the right, it will show 5 notches in the right direction, but if I aim to the right and a little bit forward, it will show 4 notches to the right and zero notches forward, until I move it enough forward to reach some threshold that lights up the first forward notch.

This leads me to believe the problem might be not that the values aren't high enough, but that I'm losing precision somewhere and sending low values to the surrounding directions of the one being currently pressed.

**Comment by Raicuparta** [comment] 2020-02-08 13:10
Fixed in 0.20

**Comment by Z5aI69A61** [comment] 2020-08-01 21:59
@Raicuparta Idk if you just dropped it or if you fixed it, but I'm still experiencing this issue. SteamVR reads the trackpad input as maxed out, but I only get 4 notches of thrust.

**Comment by Raicuparta** [comment] 2020-08-01 22:22
@Z5aI69A61 I was to reproduce, but only for forward / backward / left / right, not for up / down. Same for you?

**Comment by Z5aI69A61** [comment] 2020-08-01 22:30
@Raicuparta Yeah. Up and down uses the triggers rather than the touchpad, which caps at 5 like it should.

**Comment by Raicuparta** [comment] 2020-08-02 09:22
Closed again by #323

**Closed by Raicuparta** 2020-08-02 09:22 UTC
Labels: bug
