### ISSUE TITLE
Brittle hollow quantum tower issue

### ISSUE THREAD

**Issue by mamefan** [Raicuparta/nomai-vr#399] opened 2021-03-21 03:50 UTC
* Game Version: latest Steam
* OWML Version: latest (green in manager)
* NomaiVR Version: 1.3.3 (green in manager)
* VR hardware: Index

When I'm standing outside it on the surface, I'm finding multiple times that my belt tools go away and won't come back. Also, I'm unable to get out of the ship cockpit. That happened when I was at the white hole (quantum tower had been sucked into the brittle hollow black hole), and I wanted to get out to investigate the quantum tower but couldn't get out of my cockpit seat. The trackpad button (valve index) wouldn't let me get out.

**Comment by artumino** [comment] 2021-03-27 02:07
To add to this the toolbelt disappearing is triggered 100% of the times when using the probe launcher while a tutorial popup is opened (like the one that tells you to shoot the scout). When the toolbelt is gone the laser pointer and the ability to interact with anything are also disabled, the only way to get it working again is to pickup an item from the ground.

@Raicuparta if you are not already working on it I can have a look at it

**Comment by Raicuparta** [comment] 2021-03-27 15:18
@artumino I haven't started to look at this, so feel free. I wonder if this was a regression caused by a post-1.0.0 update, since I don't remember anyone mentioning this before recently.

**Comment by artumino** [comment] 2021-03-27 21:01
Should be addressed in #401 if we don't want to use reflection we'll find a way later

**Closed** 2021-03-28 00:49 UTC
Labels: bug
